graph LR
    subgraph ESP32["ESP32 Module"]
        ESP_3V3["3.3V"]
        ESP_EN["EN"]
        ESP_GND["GND"]
        ESP_IO0["IO0"]
        ESP_IO2["IO2"]
        ESP_IO4["IO4"]
        ESP_IO5["IO5"]
        ESP_IO12["IO12"]
        ESP_IO13["IO13"]
        ESP_IO14["IO14"]
        ESP_IO15["IO15"]
        ESP_IO18["IO18"]
        ESP_IO19["IO19"]
        ESP_IO21["IO21"]
        ESP_IO22["IO22"]
        ESP_IO23["IO23"]
        ESP_IO25["IO25"]
        ESP_IO26["IO26"]
        ESP_IO27["IO27"]
        ESP_IO32["IO32"]
        ESP_IO33["IO33"]
        ESP_IO34["IO34"]
        ESP_IO35["IO35"]
        ESP_RX["RX0"]
        ESP_TX["TX0"]
    end
    
    subgraph OLED["OLED Display"]
        OLED_VCC["VCC"]
        OLED_GND["GND"]
        OLED_SCL["SCL"]
        OLED_SDA["SDA"]
    end
    
    subgraph NFC["NFC Module"]
        NFC_VCC["VCC"]
        NFC_GND["GND"]
        NFC_MISO["MISO"]
        NFC_MOSI["MOSI"]
        NFC_SCK["SCK"]
        NFC_CS["CS"]
        NFC_IRQ["IRQ"]
    end
    
    subgraph SUBGHZ["Sub-GHz Transceiver"]
        SUBGHZ_VCC["VCC"]
        SUBGHZ_GND["GND"]
        SUBGHZ_MISO["MISO"]
        SUBGHZ_MOSI["MOSI"]
        SUBGHZ_SCK["SCK"]
        SUBGHZ_CS["CS"]
        SUBGHZ_RST["RST"]
    end
    
    subgraph POWER["Power Circuit"]
        BAT["Battery+"]
        BAT_NEG["Battery-"]
        TP4056["TP4056"]
        BOOST["5V Boost"]
        REG_3V3["3.3V Regulator"]
    end
    
    %% Connections
    ESP_3V3 --- OLED_VCC
    ESP_GND --- OLED_GND
    ESP_IO21 --- OLED_SCL
    ESP_IO22 --- OLED_SDA
    
    ESP_3V3 --- NFC_VCC
    ESP_GND --- NFC_GND
    ESP_IO19 --- NFC_MISO
    ESP_IO23 --- NFC_MOSI
    ESP_IO18 --- NFC_SCK
    ESP_IO5 --- NFC_CS
    ESP_IO26 --- NFC_IRQ
    
    ESP_3V3 --- SUBGHZ_VCC
    ESP_GND --- SUBGHZ_GND
    ESP_IO19 --- SUBGHZ_MISO
    ESP_IO23 --- SUBGHZ_MOSI
    ESP_IO18 --- SUBGHZ_SCK
    ESP_IO15 --- SUBGHZ_CS
    ESP_IO14 --- SUBGHZ_RST
    
    BAT --- TP4056
    BAT_NEG --- TP4056
    TP4056 --- BOOST
    BOOST --- REG_3V3
    REG_3V3 --- ESP_3V3
    
    %% Add resistors and capacitors
    R1["R1\n10kΩ"] --- ESP_EN
    ESP_EN --- ESP_3V3
    
    C1["C1\n10μF"] --- ESP_3V3
    C1 --- ESP_GND
    
    C2["C2\n0.1μF"] --- OLED_VCC
    C2 --- OLED_GND