[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
	z3t0/IRremote@^4.2.0

lib_extra_dirs = 
    ~/Documents/Arduino/libraries
    C:/Users/HomePC/Documents/Arduino/libraries

build_flags = 
	-D CORE_DEBUG_LEVEL=5
	-O2
	-D LED_BUILTIN=2
